### ISSUE TITLE
heroku and deployment.

### ISSUE THREAD

**Issue by monicagangwar** [MDLTechUniversity/panpage#6]
read up and tried on how to deploy builds on heroku.

**Comment by skeep** [comment]
https://devcenter.heroku.com/categories/nodejs

**Comment by monicagangwar** [comment]
this was the first thing that i tried. i also tried to deploy a html page only, it worked. now just playing around with it to explore more

**Comment by Mnw2212** [comment]
This is done as well, can we close this issue ?
