### ISSUE TITLE
Flexbox, BEM

### ISSUE THREAD

**Issue by vatsalya25** [MDLTechUniversity/panpage#7]
read about flexbox model and about BEM naming convention

**Comment by skeep** [comment]
* https://css-tricks.com/bem-101/
* http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/

**Comment by vatsalya25** [comment]
http://codepen.io/team/css-tricks/pen/EaJEBZ

Accordian struct using BEM
