### ISSUE TITLE
Flexbox and Media Query

### ISSUE THREAD

**Issue by goswamipronnoy** [MDLTechUniversity/panpage#8]

**Comment by skeep** [comment]
* https://www.smashingmagazine.com/2015/08/flexible-future-for-web-design-with-flexbox/
* http://marketblog.envato.com/learn-something-new/css3-flexbox/
* http://blog.teamtreehouse.com/responsive-design-of-the-future-with-flexbox
* https://www.new-bamboo.co.uk/blog/2014/03/10/flexboxes-media-queries-awesome-layouts/

**Comment by goswamipronnoy** [comment]
- http://flexbox.io/#/
- https://bocoup.com/weblog/dive-into-flexbox
- https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries
