### ISSUE TITLE
Continuous Integration using CircleCI

### ISSUE THREAD

**Issue by Mnw2212** [MDLTechUniversity/panpage#9]
Integrating code at every commit and deploying on heroku if all the tests pass ,alert the user otherwise
Setting up the circle YAML for precise environment testing

**Comment by skeep** [comment]
https://circleci.com/integrations/heroku/

**Comment by Mnw2212** [comment]
Basic integration is tested and working.
Process ::
=> commit to repo on github
=> CircleCI will build and test for integration errors
=> If no error exists, the master branch will be deployed on Heroku

Current test repository : 
https://github.com/mnw2212/gittest
==> any commit on this repo will update here
http://integrationtestmdl.herokuapp.com/

**Comment by Mnw2212** [comment]
This is done , so can we consider this as completed ?
